### ISSUE TITLE
Fix currencylayer

### ISSUE THREAD

**Issue by Zapata** [Zapata/bitshares-pricefeed#4]
```
______________________________________________________ test_currencylayer_fetch _______________________________________________________

checkers = <class 'conftest.Checkers'>

    def test_currencylayer_fetch(checkers):
        source = CurrencyLayer(quotes=['BTC', 'EUR'], bases=['USD'], api_key=os.environ['CURRENCYLAYER_APIKEY'], free_subscription=True)
        feed = source.fetch()
>       checkers.check_feed(feed, ['BTC:USD', 'EUR:USD'], noVolume=True)

tests/sources/test_currencylayer.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

feed = {}, pairs = ['BTC:USD', 'EUR:USD'], kargs = {'noVolume': True}, pair = 'BTC:USD', quote = 'BTC', base = 'USD'
@py_assert1 = False, @py_format3 = "'USD' in {}", @py_format5 = "assert 'USD' in {}"

    @staticmethod
    def check_feed(feed, pairs, **kargs):
        print(feed)
        for pair in pairs:
            (quote, base) = pair.split(':')
>           assert base in feed
E           AssertionError: assert 'USD' in {}

tests/sources/conftest.py:9: AssertionError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------

CurrencyLayer encountered an error while loading live data.
{}
-------------------------------------------------------- Captured stderr call ---------------------------------------------------------
Traceback (most recent call last):
  File "/home/zapata/Projects/bitshares/bitshares-pricefeed/wrappers_env/lib/python3.6/site-packages/bitshares_pricefeed-0.0.10-py3.6.egg/bitshares_pricefeed/sources/main.py", line 65, in fetch
    feed = self._fetch() # pylint: disable=no-member
  File "/home/zapata/Projects/bitshares/bitshares-pricefeed/wrappers_env/lib/python3.6/site-packages/bitshares_pricefeed-0.0.10-py3.6.egg/bitshares_pricefeed/sources/currencylayer.py", line 25, in _fetch
    raise Exception(result.get("description"))
Exception: None
```

**Comment by Zapata** [comment]
False positive, works while running the unit test unitary.
