### ISSUE TITLE
Fix OKCoin

### ISSUE THREAD

**Issue by Zapata** [Zapata/bitshares-pricefeed#6]
```
__________________________________________________________ test_okcoin_fetch __________________________________________________________

checkers = <class 'conftest.Checkers'>

    def test_okcoin_fetch(checkers):
        source = Okcoin(quotes=['BTC'], bases=['USD', 'CNY'])
        feed = source.fetch()
>       checkers.check_feed(feed, ['BTC:USD', 'BTC:CNY'])

tests/sources/test_okcoin.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

feed = {}, pairs = ['BTC:USD', 'BTC:CNY'], kargs = {}, pair = 'BTC:USD', quote = 'BTC', base = 'USD', @py_assert1 = False
@py_format3 = "'USD' in {}", @py_format5 = "assert 'USD' in {}"

    @staticmethod
    def check_feed(feed, pairs, **kargs):
        print(feed)
        for pair in pairs:
            (quote, base) = pair.split(':')
>           assert base in feed
E           AssertionError: assert 'USD' in {}

tests/sources/conftest.py:9: AssertionError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------

Okcoin encountered an error while loading live data.
{}
-------------------------------------------------------- Captured stderr call ---------------------------------------------------------
Traceback (most recent call last):
  File "/home/zapata/Projects/bitshares/bitshares-pricefeed/wrappers_env/lib/python3.6/site-packages/bitshares_pricefeed-0.0.10-py3.6.egg/bitshares_pricefeed/sources/main.py", line 65, in fetch
    feed = self._fetch() # pylint: disable=no-member
  File "/home/zapata/Projects/bitshares/bitshares-pricefeed/wrappers_env/lib/python3.6/site-packages/bitshares_pricefeed-0.0.10-py3.6.egg/bitshares_pricefeed/sources/okcoin.py", line 20, in _fetch
    result = response.json()
  File "/home/zapata/Projects/bitshares/bitshares-pricefeed/wrappers_env/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Zapata** [comment]
Fixed by b0bbe58b714127a55bb3736d18b76b159344acd0
